### ISSUE TITLE
Change over to anchor tagging for translation stitching

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#10]
As we talked about!

**Comment by ebeshero** [comment]
Thanks, @setriplette ! @HelenaSabel This is for the coding we're using to "stitch" passages from Southey to the clause units we've been marking in Montalvo. Stacey and I worked on some of this tagging today to see what we could see and to think about how it needs to work, and what kinds of information we want to collect in this markup. Since we're using `<milestone/>` to do so much with all that dialogue, we realized the tagging was getting a little dense and confusing to apply (just hard on our human eyes), so we decided to use the self-closing <anchor/> element instead to mark Southey's translation units. I'll work on updating the Schematron for that!

**Comment by ebeshero** [comment]
Aha! @setriplette :  I discover that the TEI `<anchor/>` element doesn't accept an `@unit` attribute. But guess what? It's fine--because in our project the new element `<anchor/>` will convey on its own that it's a "stitchery" unit to associate passages of a translation with a source text. 

So our new tagging for this will be a little simpler (and hooray for fewer attributes!):

`<anchor ana="start" synch="#M20_p1_c1"/>`

I'm writing up an identity transformation to convert the "transUnit" milestones over to anchors, and @HelenaSabel you'll want to see this, as I'm trying out the new XSLT 3.0 built-in template for shallow-copy to do the identity transformation this time!

**Comment by ebeshero** [comment]
Done! Ran the identity transformation to change the old `milestone unit='transUnit'/>` elements over to simple `<anchor/>` elements. Updated our Schematron to reflect this, and to outlaw any future uses of `milestone unit='transUnit'/>`.

**Comment by HelenaSabel** [comment]
That's very cool (and a motivating reason to explore oXygen and choose it over the command line)
