### ISSUE TITLE
Southey 21 has been synched

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#12]
Elisa, could you take a look at this and see if this is what you had in mind?

**Comment by ebeshero** [comment]
@setriplette You mean this commit, right? https://github.com/ebeshero/Amadis-in-Translation/commit/1e36ea71e081f4bc54e2ded54e12803fe7643207

**Comment by ebeshero** [comment]
Yes, this is how the "stitchery" coding was going to work the way we discussed it, to mark which parts of Southey coincide with specific "chunks" or locations in Montalvo. 
So, next, after we've done a reasonable selection of these (and I need to deliver you more Southey chapters!) we'll need to work on extracting information about the translation units into a readable format for us to review and process for what we want to measure.

Okay--so this is the next new thing we need to brainstorm! What do we want to do with these matched up units? I imagine 
- we will care about any place where there's a gap and Southey skips ahead or backward.
- we want to count the words in between each start and end anchor, and compare the wordcounts to the matched unit in Montalvo. I was going to do this by counting white spaces. 

Probably we could start with a great big XML table of the units by chapter, side by side with wordcounts. 

We could make another, smaller chart that only highlights points of extreme alteration so we can zoom to those.

Would we want to apply classifications to the kinds of changes Southey is making? We could do that in the Southey XML files by adding some attributes, or we could do that as you're surveying the charts: We'd make the charts in XML so we could add some analytical markup there.

Ahhh, here's where the hard work begins! :-) 

We're thinking of two kinds of visualization:
1) **Montalvo side-by-side with Southey**: made with alignment on-click, so that when you click on a clause unit in a Montalvo chapter, you pull up the matching passage in Southey. And we highlight anything in Southey that doesn't correspond to anything in Montalvo (and vice versa). 

2) **Charts (and graphs)** to help us study the kinds of changes Southey is making to Montalvo. (I say we start by just extracting side-by-side information, giving it to @setriplette to study, and then figuring out what new markup to add if we want to classify kinds of alteration (or decide if we don't). Maybe all that matters for the moment is noting compression points--where Southey compressed Montalvo significantly and highlighting what's missing. 

@setriplette @HelenaSabel

**Comment by ebeshero** [comment]
PS: The Southey transcription is going much faster now. I'm working with that other GitHub edition of Amadis written in markdown, and I'm just repairing it as I go by checking it against my facsimile of the 1803 edition. It's still slow and careful work, but saves a step. @setriplette I've been working on the early chapters in order. Should I still do that, or do you want me to skip ahead and fill in some of the chapter 20-somethings where you're working?

**Comment by HelenaSabel** [comment]
I can picture the first type of visualization with a color-coded highlighting as Juxta and other collation tools do. 
Graphs with the different reasoning behind the gaps by Southey would be a great analytical visualization. I think this kind of attributes that describe the modifications would be easier to add after retrieving and matching the text,  and doing the charts. The word counting might not be as informative, though.
I'll keep working on the transcription of chapter 2 and following chapters in two weeks, so it may be better if @ebeshero skip ahead... Sorry!

**Comment by setriplette** [comment]
From the chapter I did, I observed lots of compression—skipped clauses and shortened clauses, with occasional reordering in order to eliminate repetition. Southey does add some ideas that are not present in the original, primarily adverbs and specifications of unclear antecedents (in one case attributing an action to a different character, either because he liked that idea better or because he misread the Spanish).

I think word counting in the individual clauses—or at least in the whole chapter--might help us see how much Southey removed. A scholarly translation in the 21st century would not make nearly so many interventions, and the overall result is an abridgment as well as a translation.

S
—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Sep 18, 2015, at 1:01 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

I can picture the first type of visualization with a color-coded highlighting as Juxta and other collation tools do.
Graphs with the different reasoning behind the gaps by Southey would be a great analytical visualization. I think this kind of attributes that describe the modifications would be easier to add after retrieving and matching the text, and doing the charts. The word counting might not be as informative, though.
I'll keep working on the transcription of chapter 2 and following chapters in two weeks, so it may be better if @ebesherohttps://github.com/ebeshero skip ahead... Sorry!
