### ISSUE TITLE
Whether to continue with `<milestone/>` or not: (was: Southey Ch 22 ready for stitchery by Stacey)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Amadis-in-Translation#15]
@setriplette Southey 22, as well as Southey 1 and 2 are ready for stitching. I shall continue on with Southey 23!

**Comment by setriplette** [comment]
Hi Elisa and Helena!

I’m looking for a way to code the places where Southey changes dialogue in Montalvo to indirect discourse, as in

The king said: “What do you have to talk about with the king’s squire?” v. in Southey “The king asked her what she had to talk about with the king’s squire.”

I’ve been putting them in <anchor ana=“start” type=“add”/> for right now, but I’d like to mark in some way that it’s direct to indirect discourse since Southey talks about doing this in his preface.

Thoughts?

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Sep 24, 2015, at 1:20 AM, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #15https://github.com/ebeshero/Amadis-in-Translation/issues/15 to @setriplettehttps://github.com/setriplette.

**Comment by HelenaSabel** [comment]
I think I'd use a new value for @type. Maybe "report" (or "reported"), if we want to be very specific, or "style" if we want to create a more generic category to fit other changes related to the writing style.

**Comment by setriplette** [comment]
Thanks for the suggestions!. I’m going to use type=“report” for this. It’s going to be very frequent.

I might save type=“style” for something else.

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Sep 24, 2015, at 6:01 PM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I'd use a new value for @typehttps://github.com/type. Maybe "report" (or "reported"), if we want to be very specific, or "style" if we want to create a more generic category to fit other changes related to the writing style.

**Comment by ebeshero** [comment]
@setriplette @HelenaSabel Hmmm. I was thinking about this while working on Ch. 22 yesterday--lots and lots of indirect discourse in Southey! I'm glad you're thinking about it, too. My first thought was, if we coded it, we should maybe use the <milestone/> element, which is storing information about speech-acts. <anchor/> is what we're using to distinguish where Montalvo connects with Southey.

Does it make sense to store the attribute on the <anchor/> element that holds the "stitchery" info? Or does it make sense to have a separate <milestone/> element for the speech portion, that describes Southey's handling of speech? 

I think the attribute value we use for @type should be "indirect" if it goes on milestone. And that makes me think we might want to globally convert all the @type="said" should change to "direct". That would work if *all* the <milestone/> elements only ever hold information about the designation of speech acts in Amadis. What think you both, team Helistacea?

**Comment by ebeshero** [comment]
@setriplette @HelenaSabel 
Hmmm. I was thinking about this while working on Ch. 22 yesterday--lots and lots of indirect discourse in Southey! I'm glad you're thinking about it, too. My first thought was, if we coded it, we should maybe use the `<milestone/>` element, which is storing information about speech-acts. `<anchor/>` is what we're using to distinguish where Montalvo connects with Southey.

Does it make sense to store the attribute on the `<anchor/>` element that holds the "stitchery" info? Or does it make sense to have a separate `<milestone/>` element for the speech portion, that describes Southey's handling of speech?

I think the attribute value we use for @type should be "indirect" if it goes on `<milestone/>`. And that makes me think we might want to globally convert all the @type="said" to "direct". That would work if all the `<milestone/>` elements only ever hold information about the designation of speech acts in Amadis. What think you both, team Helistacea?

**Comment by ebeshero** [comment]
@setriplette @HelenaSabel Wait a second. My comments above were confused about the attributes on `<milestone/>`. Here's what I'm really suggesting:
1) Use `<milestone/>` for anything to do with speech whatsoever. So we can set up a system of attributes and values on that element to store all the information about the handling of speech acts across our files, whether in Montalvo or Southey.
2) If we use `<milestone/>`, we add a new value to the @unit attribute, so it's either "direct" or "indirect." Does that make sense? Currently we have @unit="said", but I think we now want to use the attribute values to distinguish between different kinds of speech acts, if we are deciding to use `<milestone/>` to store only information about characters speaking. 

Does this work, Stacey and Helena? Whatever we decide, we'll put it up in a wiki, and I'll add it to the Schematron!

**Comment by ebeshero** [comment]
Also, if we decide to change our attribute values for `@unit="said"` to `@unit="direct" | "indirect"`, it'll be a chance for me to try running an Identity Transformation XSLT over the batch of our project files so far! (Yay!) ;-) It wouldn't be a pain to make the change.

**Comment by setriplette** [comment]
Hi all,

My two cents:

I don’t want to add too much complication, as the dialogue tagging is making things hard to read as is. I have been trying to mark big changes between the original and the translation, which is why the indirect discourse is useful, because Southey uses it to condense number of words. I really don’t want to be tagging every indirect discourse on top of that, which would give us no extra hits in Montalvo (technique not developed yet) and duplicates in the Southey (they would already be tagged as differences from the original).

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Sep 24, 2015, at 8:42 PM, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> wrote:

Also, if we decide to change our attribute values for @unit="said" to @unit="direct" | "indirect", it'll be a chance for me to try running an Identity Transformation XSLT over the batch of our project files so far! (Yay!) ;-) It wouldn't be a pain to make the change.

**Comment by ebeshero** [comment]
@setriplette Can you explain what you mean by "hits in Montalvo"? I'm not sure I'm following you: When is indirect discourse relevant to mark, and when isn't it? 

If we use the `<milestone/>` element to designate speech of any kind (direct or indirect), that would give us a consistent use of this element. But I'm sensing that you'd rather be storing information about indirect discourse in Southey in the `<anchor>` element, and I'm now wondering if all the information about speech should be stored there. 

Here's the issue: The `<anchor/>` element is telling us where passages in Montalvo align with passages in Southey. How do we imagine accessing information about speech acts connected with these passages? Does that information need to be stored in the `<anchor/>` element for us to access it at all? No--but it's easier to get if it's an attribute on the element. We can search for `<milestone/>` elements that are positioned in between the "start" and "end" <anchor/> elements for a particular passage: it would be to search for following-sibling elements called milestone who themselves are followed by an anchor end element. The XPath is a little tricky but it's well within our reach--we can write it. 

So, for me it's now a question of what the `<milestone/>` elements are to be used for. Does it make sense only to use them for direct speech acts? If so, why?

**Comment by ebeshero** [comment]
@setriplette @HelenaSabel  Sorry for being difficult about this--it's just I was thinking about the `<milestone/>` markup a lot yesterday as I had a lot of it to apply in Southey Ch 22, and I've been thinking about how we'll be accessing that info as we're gearing up to write more XSLT for the project. So it may sound like I'm trying to "reinvent the wheel" but it's just that I want to make sure we understand what the speech tagging is good for and how we want to use it. 

The question about what we store in `<anchor/>` is kind of a big deal, because I might be misunderstanding what you want to do with it. If it just matters to signal that Southey altered the indication of speech acts in Montalvo by applying indirect discourse, and we don't care about marking exactly where Southey applies that, then a simple attribute signal in `<anchor/>` makes sense. But I guess I was going the other way and wondering if we might want a literal marker of the indirect discourse in the text. We could always go back and apply that markup later, I suppose. But might we want to trace how much indirect discourse Southey is applying? We do already have a good (or at least functional) mechanism for doing that with the `<milestone/>` element. I don't mind applying the markup. 

The other direction we might take is simply to stop using `<milestone/>` if it's too cluttered and too much trouble. We could apply an attribute on the `<anchor/>` element that signals either direct or indirect discourse is present in a particular span of Southey text. `<anchor/>` doesn't always span the same way as `<milestone/>` does, so we might be running into issues of overlap and entanglement (even though we're using self-closing elements). Let's give it some thought, to determine really _how precise_ we want our markup of direct and indirect speech to be. I suppose I'm leaning to more precision, but that may not be what we really want.

**Comment by setriplette** [comment]
Hi Elisa,

I’ll try to explain what I meant, because it’s entirely possible that you and I mean different things by direct and indirect discourse. I guess I’m having envisioning what we could analyze with <milestone> tagging.

But first the terminology!

What I mean by direct discourse is dialogue, for example:

The king said: “why are you talking to the Perion's squire?”

She said: “I am worried that Perion will not be comfortable sleeping in the same room with you!"

We’ve been marking this in <milestone>, and in my mind it’s difficult to tag. It’s been a thorn in my side because of all the interruptions, and because it’s hard for me to see where to put anchors because the texts are crowded with milestone elements. What are you planning on using the milestones for? I suppose we could generate statistics on what percentage of the text is dialogue, or on how many speeches an individual character makes, but I’m not sure what the data would tell us. Did you have something in mind?

What I mean by indirect discourse is reported speech, as in the examples below:

The king asked the maid why she was talking to Perion's squire.

She said that she was worried that Perion would not be comfortable sleeping in the same room with the king.

One of the reasons Montalvo’s text is so long is that it has almost no reported speech/indirect discourse. Beatriz Bernal starts using reported speech halfway through her romance (written 1530s). I felt like cheering for her when I noticed it because it seemed to me she was discovering how to manipulate one of the building blocks of the modern novel all on her own.

A simple-seeming use of indirect discourse, like the following example, would not be frequent in Montalvo:

The squire told them that Amadís and Oriana were eating a nice picnic on the riverbank.

 In Montalvo, I’d expect something clumsier and less modern, like:

 The squire said to them. Amadís and Oriana are eating a picnic: They are on the riverbank/ It is nice.

This is what Helena and I are having to deal with—Montalvo’s narration can be interesting in and of itself, but to those accustomed to the modern novel it must seem highly defective. I wouldn’t swear there is NO indirect discourse in Montalvo, but I’m not in favor of going back through the chapters and hunting for it because I’m not sure what argument we’d make about it if we found any. Such data would probably show us that Montalvo’s use of direct and indirect discourse is typical for the 1490s, but I don’t know how we’d quantify what exactly is “normal" without a larger bank of texts from the time period. Which would take us far afield from our interest in Southey.

I should explain why indirect discourse seems “modern” to me, and why it feels “normal” for a 19th c writer and “abnormal” for a 15th c one. Language teachers make a big deal of indirect discourse and present it as a separate category from direct discourse because, as you can see from my examples, it requires a sequence of tenses in the past to report information that could be rendered in the present in direct discourse. It requires writers to manipulate a mix of present, preterit, imperfect, and conditional in Spanish. (Elisa--English has only one past tense where Spanish has two aspects on the past, preterit and imperfect, which are similar to the passé composé v. imparfait that you’ll be familiar with from French).

Indirect discourse is difficult for students to learn, difficult to write in, and on the whole, more linguistically complex than direct discourse. However, it is very easy on the reader, and it is one of the things that makes long novels bearable—it’s a short format for going back over information the reader already knows, as opposed to repeating it all whenever a new character arrives on the page and needs to be told something. The use of indirect discourse also makes the novel more distinct from theatre. Spanish prose of the 15th-16th century often reads like theatrical monologues in sequence (Helena: I’m thinking about La cárcel de amor and La Diana specifically). Maybe this could be considered “novelistic” at a stretch (Heliodorus’s Ethiopian History reads like a sequence of theatrical monologues, and scholars classify it as an “ancient novel”), but it definitely isn’t “modern."

Indirect discourse is not the same as free indirect discourse, which I consider even more modern (I’m associating the development of it in my head with Jane Austen, and specifically with the portion of Pride and Prejudice where the narrator explores Elizabeth’s changing feelings about Darcy’s letter, but I could be wrong about my example). I would describe free indirect discourse as the narrator slipping into the thoughts of the character and engaging in subjective narration. At it’s simplest (and Elisa you can correct me here bc you teach this century), I believe free indirect discourse would be indirect discourse without attributions like “he thought” or “she felt.” I know from experience that this is even harder to do correctly when you’re writing, and I haven’t seen any examples of it in the Southey translation. In the Montalvo—definitely not. Characters don’t really even have that kind of interiority in a late medieval prose work. All their emotions are externalized and expressed through physical transformations of the body.

In sum: Southey is full of indirect discourse where Montalvo is full of direct, but this is not necessarily interesting.

Southey is writing in the first decade of the 19th century. We expect him to be writing a modern novel. Thus, the fact that he uses indirect discourse more than Montalvo does in 1490 doesn't tell us anything we didn’t know about these two texts before we started a digital humanities project on them. I’m hesitant to go back through the Montalvo looking for the few instances of indirect discourse there might be when I could be using that time instead to move forward on what we’re already doing.

And now about <anchor>. I’ve been using <anchor> to mark what I perceive to be Southey’s translation choices. I hope that my tags will let us count and describe the places where Southey left out clauses, reversed the order of clauses, interrupted one clause with another (interleaving portions of them), shortened clauses, or turned direct discourse into the more modern, shorter indirect discourse. The indirect discourse isn’t an issue for me in and of itself—I’m not interested in writing a paper on indirect v. direct discourse. I see Southey’s reported speech as a translation choice, and probably also a cultural adaptation to the context of the modern novel, and in that sense, it is one element among many that I might talk about. I’m already marking it in the Southey with the type=“report” that Helena suggested.

The bigger issue with the <anchor> tags is that I do not know what they are going to tell us yet. I am hoping at this point for something publishable, but right now all I can say is that I am interested to see what exactly Southey had to do to adapt Montalvo’s very long, very repetitive text with all its typical chivalric and/or medieval prose features to the language, culture, and literary tastes of the English 19th c.

In that vein...

The other thing I’m using <anchor> to mark is where Southey adds something new to Montalvo, using type=add. I reserve type=add for words and phrases for which I can’t find antecedents in Montalvo. I haven’t included what I consider slight misreadings in this category. Every translation is full of moments where the translator pushes against the sense of the original, and my vocabulary choices might be no more exact than Southey's. Type=add marks what I judge to be deliberate additions, usually transitional devices like adverbs, but sometimes entirely different linguistic formulations, almost always shorter than the original. Southey’s additions don’t really anchor to anything, but they sit between Montalvo's clauses and are in a sense connected to the Montalvo clauses on either side, so that’s how I’ve justified using <anchor> to find them.

Once again, I don’t know what we’ll do with these additions until I have a lot of them to consider together.

Maybe I’m just not sure, Elisa, what you envision doing with all the indirect or direct discourse. I have to say, I’m already over my head with <milestone>, and I am definitely hesitant to tag more things without a good reason to do so.

Hugs,
S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Sep 25, 2015, at 12:47 AM, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> wrote:

@setriplettehttps://github.com/setriplette @HelenaSabelhttps://github.com/HelenaSabel Sorry for being difficult about this--it's just I was thinking about the <milestone/> markup a lot yesterday as I had a lot of it to apply in Southey Ch 22, and I've been thinking about how we'll be accessing that info as we're gearing up to write more XSLT for the project. So it may sound like I'm trying to "reinvent the wheel" but it's just that I want to make sure we understand what the speech tagging is good for and how we want to use it.

The question about what we store in <anchor/> is kind of a big deal, because I might be misunderstanding what you want to do with it. If it just matters to signal that Southey altered the indication of speech acts in Montalvo by applying indirect discourse, and we don't care about marking exactly where Southey applies that, then a simple attribute signal in <anchor/> makes sense. But I guess I was going the other way and wondering if we might want a literal marker of the indirect discourse in the text. We could always go back and apply that markup later, I suppose. But might we want to trace how much indirect discourse Southey is applying? We do already have a good (or at least functional) mechanism for doing that with the <milestone/> element. I don't mind applying the markup.

The other direction we might take is simply to stop using <milestone/> if it's too cluttered and too much trouble. We could apply an attribute on the <anchor/> element that signals either direct or indirect discourse is present in a particular span of Southey text. <anchor/> doesn't always span the same way as <milestone/> does, so we might be running into issues of overlap and entanglement (even though we're using self-closing elements). Let's give it some thought, to determine really how precise we want our markup of direct and indirect speech to be. I suppose I'm leaning to more precision, but that may not be what we really want.

**Comment by ebeshero** [comment]
@setriplette @HelenaSabel Sorry for my delayed response--it's been a long day here, and I wanted time to properly read and think about this. Yes, you and I mean the same thing when we refer to direct vs. indirect discourse. I wonder if want the `<milestone/>` tagging at all now. Let's review what we had in mind for it--at least what I remember from our conversations last summer.

We wanted to track how much of either text was written in direct speech, and we wanted to associate particular speech acts with particular characters. We developed schema rules so that every @start on a `<milestone/>` element would signal an active speaker, and we imagined ourselves collecting information on the number of words uttered by particular characters. We wanted to be able to compare how much direct speech is attributed to characters in Montalvo vs. the same characters in Southey. Using the `<milestone/>`, defined as we've defined it, allows us precisely to grab every word attributed as direct speech to a character. I agree, it's tiresome to add the tagging even to Southey, but that, as I recall, was our goal in doing it. I didn't properly realize how very much of it you and Helena have to mark in Montalvo! Then again, does it give us interesting data to compare? 

Perhaps for our preparations for the TEI Conference, since we're modelling just enough of Amadis-in-Translation to investigate our coding strategies on a longer project, we should consider our `<milestone/>` markup to be an experiment that we apply to just the few chapters we've coded so far: Do we have enough of a sample here to do that comparison and see if it suggests something interesting--to tell us whether we should continue applying it to other chapters? Maybe we've done enough _for now_, and don't need necessarily to continue with it because we can always add it later.

I'm thinking perhaps what you're thinking: We're realizing that what's _really_ interesting here isn't so much when Southey _duplicates_ the standard practice of direct speech, but when he _alters_ it to make it _indirect._ That _those_ instances deserve our attention. And therefore we need to change our coding strategy to match. 

Perhaps our `<anchor/>` markup, too, is sufficient by itself to encode information about each unit of Southey that correlates to a unit of Montalvo, that it can _characterize_ that correlation rather than necessarily _quantify_ it. So we can, in the anchor elements, hold information that Southey _converted_ a passage of direct speech in Montalvo over to indirect, and we can count the number of passages where that conversion happened, without counting the number of words involved. 

Here's a question, then: Do we want to signal somehow that a given clause unit in Montalvo simply contains _speech_ of either the direct or the indirect kind (not expecting we'll ever see the latter, but we _could_ be surprised)?  And then in the corresponding `<anchor/>` element in Southey, do we want to do the same kind of signalling with the same attribute and value set, to indicate "direct" or "indirect" speech?

This would involve simplifying and modifying our tagset a bit. I think we should not scrap any of the ornate coding we've already been applying, but we should make a decision now about 
1) whether to continue as we have with `<milestone/>` or
2) stop using `<milestone/>` and store information in attributes on `<cl>` and `<anchor/>` elements in Montalvo and Southey chapters respectively.

I'm happy to go with decision 2, if that saves us time and would give us the information we care about most in studying how Southey's translation alters Montalvo. What do you each think?

**Comment by ebeshero** [comment]
@setriplette Aside (not entirely unrelated): We're scheduled for Saturday 10/31 at the TEI Conference! http://tei2015.huma-num.fr/en/papers/

And I'm on for Fri. 10/30 with Erica and Molly with the "Finding Miss James" paper! (Oi!)

**Comment by setriplette** [comment]
Hmm.

I think I am in favor of continuing with <milestone> just until the conference and seeing if we can get anything out of it just for the short term. We’re really just talking about another 2-3 new chapters on this model. It might let us make some more visualizations for the conference.

But yes, I think milestone is of limited use to us now that we actually see how these two texts work together. That a character utters a large amount of dialogue in Montalvo is not interesting because they all do—even the unnamed ones talk endlessly. I think the type=report attribute inside <anchor> is much more promising because it signals Southey’s process. It strikes me that since we’re looking at the texts this closely, we’re actually duplicating that process in a sense. It gives me enormous respect for Southey as a translator.

I’m working with the 1540 French and 1618 English translations in the traditional way right now, and it’s interesting to see how Herberay and Munday negotiate these issues differently. I suppose it should not surprise me, given the Romantic value for antiquarianism and the medieval era more specifically, that Southey’s is actually the best translation by a modern standard. He’s definitely the best Hispanist—Herberay knew the language but not the culture, and he just didn’t get the whole concept of honra and didn’t even bother translating anything to do with it. You should see the sex scenes that he adds in all the space he saved! Yesterday I found a rather florid undressing scene with "alabaster globes” (ugh, such poor taste) that is not present at all in Montalvo. I can see now why it was such a scandal that Mary Wroth read Amadís and wrote continental-style romance; what the English context knew of Amadís was in fact as filthy as only early modern French can be. It’s almost at that Rabelaisian level of bodily detail. Elisa, you’ll get to read about all of this in some distant future before I send the book out.

Elisa, I also came across the name of a woman writer, Margaret Tyler, who translated The Mirror of Princes (Espejo de principles), another Iberian romance. Do you know if she’s famous for anything else? Or maybe she translated several texts?

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Sep 26, 2015, at 5:26 AM, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> wrote:

@setriplettehttps://github.com/setriplette Aside (not entirely unrelated): We're scheduled for Saturday 10/31 at the TEI Conference! http://tei2015.huma-num.fr/en/papers/

And I'm on for Fri. 10/30 with Erica and Molly with the "Finding Miss James" paper! (Oi!)

**Comment by HelenaSabel** [comment]
One reason to keep using the <milestone/> elements (although it might not be good enough) it's that it'll help us to create human readable views of Montalvo's version. As we have mentioned before, there is no specific punctuation marks to delimit the instances of direct speech; so with the use of the <milestone/> elements we can add later on some punctuation marks or other visual tools to help the readers.

**Comment by ebeshero** [comment]
@HelenaSabel Your point reminds us we're not only analyzing the changes Southey applied, but we're also producing a searchable and readable edition of Montalvo. I think we may want to apply some XSLT transformation to experiment with visualizing what we can from our markup so far: both a reading text and some extracted information. I'll give this a try soon, and I bet Helena can give me a hand with it!  

@setriplette I'm on board with only using `<milestone/>` for direct speech, and with using `@type="report"` inside `<anchor/>` when you do the stitchery for handling indirect discourse.

**Comment by setriplette** [comment]
As much as I hate the idea of coding more milestones, I think Helena is right, and they are likely to be our most convenient way to transform dialogue for viewing. Sigh. I'm going to close this bc I'm fairly well convinced that the right thing to do is persist with milestones as we have been. Who knows, maybe we'll think of an analytic use further down the line.

**Comment by ebeshero** [comment]
Actually @setriplette and @HelenaSabel I'm reopening this with an assignment to myself to add a schematron rule for your `@type="report"` on the `<anchor/>` element. 

No--I'd not known of Margaret Tyler before this, but she seems important, and I wonder if Southey knew about her! My first thought is that the name sounded familiar and I wondered if she was Southey's friend, Mary Barker, an Englishwoman fluent in Spanish whom I think he met while traveling in Spain: She helped with a number of translation-related things (and we might want to see if she was ever involved with Amadis). He nicknamed her "the Senhora" and she was a favorite with Southey's kids. But no--Margaret Tyler is more significant than that--perhaps the first woman to write/publish a romance in England (?) and at least the first woman to translate a Spanish romance into English. Well worthy of research--I wonder if Southey knew about her?

**Comment by ebeshero** [comment]
Added that schematron rule for @type on the anchor element. Now closed!
