### ISSUE TITLE
How best to encode interpolated letters?

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Amadis-in-Translation#2]
Let's look at some options for levels of narration, and at correspondence markup in the TEI Guidelines, and consider whether we want something more or different from the milestone element here.

**Comment by HelenaSabel** [comment]
I think that we will be forced to use milestone units to avoid overlapping issues. I'm pasting here the example from chapter 1:

I find this example particularly tricky because it goes from a direct quotation to being reported. If in the letter the only written text is: "Este es Amadís Sin Tiempo hijo de rey"
Then it should be coded with something similar to this:
`< milestone unit="writtenText" resp="#Darioleta" ana="start"/>Este es <persName>Amadís Sin Tiempo</persName> hijo de rey: <milestone unit="writtenText" ana="end"/></cl>
<cl xml:id="M1_c215">y sin tiempo dezía ella porque creía que luego sería muerto:</cl>`

However, if the explanation of the name is written in the letter, I guess it should be more accurate to do something like this:
`<milestone unit="writtenText" resp="#Darioleta" ana="start"/>Este es <persName>Amadís Sin Tiempo</persName> hijo de rey :</cl>
<cl xml:id="M1_c215">y sin tiempo <milestone unit="writtenText" ana="intStart" type="reported"/> dezía ella porque creía que luego sería muerto:</cl>
<cl xml:id="M1_c216">y este nombre era allí muy preciado porque assí se llamava un sancto a quien la donzella le encomendó.<milestone unit="writtenText" ana="end"/></cl>`

**Comment by ebeshero** [comment]
Stacey and I are looking at the `<floatingText>` element in the TEI Guidelines, and we are thinking that this will work well for encoding internal levels of text, such as letters, ballads, inscriptions on sculptures, and parchments that aren't actually letters but pieces of writing that the characters encounter. Read about it here in the Guidelines: [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSFLT](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSFLT)

@HelenaSabel @setriplette

**Comment by ebeshero** [comment]
Okay--I just changed the link above to the floatingText explanation in [Chapter 4: Default Text Structure](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSFLT). Read the explanation and have a look at the examples. @setriplette will mock up an example of how to code this in Montalvo!

**Comment by setriplette** [comment]
Here is how I think we should code this:

```
<cl xml:id="M1_c213">y fizo una carta que dezía.</cl>
 <floatingText>
                <body>

                        <p><cl xml:id="M1_c214">Este es <persName>Amadís Sin Tiempo</persName>
                             hijo de rey:</cl></p>

              </body>

 </floatingText>

 <cl xml:id="M1_c215">y sin tiempo dezía ella

<!-- st 8.25.15 This part is indirect discourse and not part of the letter or floating text in and of itself. 
It's pretty normal for Amadís to quote a letter and then reiterate its content in indirect discourse. 
I don't see it as an overlap. -->

                        porque creía que luego sería muerto:</cl>

                    <cl xml:id="M1_c216">y este nombre era allí muy preciado porque assí se llamava
                        un sancto a quien la donzella le encomendó.</cl>  
```

**Comment by setriplette** [comment]
The reason I chose this is because these interpolated letters and ballads are really separate texts held inside Amadís de Gaula. The two ballads we'll see were in existence before Montalvo put them in. The letters (especially Oriana's letter in Book II) get quoted and reused in other texts.
I don't think we'll have wrapping issues, because for most of the letters the 1547 sets them off with one or more calderones. The reason it seemed we had a wrapping issue here was that the text repeated in indirect discourse what it had already told us with the interpolated letter. Amadís is in general very repetitive and we'll see this direct-indirect pattern again

**Comment by HelenaSabel** [comment]
Sounds good to me. How about adding a @resp attribute so we don't miss who are the writers of the letters?
`<floatingText resp="#Darioleta">[...]</floatingText>`

**Comment by setriplette** [comment]
Good idea!

**Comment by setriplette** [comment]
They will not always have a writer--there are some random parchments and inscriptions--but most will have a `resp` that corresponds to one of our existing xml ids

**Comment by ebeshero** [comment]
So, we'd only use `@resp` on `<floatingText>` when it's applicable. Good! :-)

**Comment by ebeshero** [comment]
Updated our Wiki on [What to do with the interpolated letters](https://github.com/ebeshero/Amadis-in-Translation/wiki/What-to-do-with-the-interpolated-letters) with the new code.
