### ISSUE TITLE
side by side visualization highlighting

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#26]
Dear Helistacean team.
I don't find the highlighting I implemented satisfying. In the first place, there is the fact that I haven't made the Southey to Montalvo highlight available yet, but that would be an easy fix. What worries me is that both versions are quite different in length, and I find problematic the fact that the counterpart highlighting might not visible on the screen... Increasing the margin between Southey's was a lazy, unsatisfactory fix. Maybe I could find a way to make both highlightings always visible )so when one isn't, the page would scroll automatically so you can see it) before you guys present in Lyon, but is there other issue about the visualizations that you find more pressing?

**Comment by ebeshero** [comment]
@HelenaSabel I had not imagined that you would be writing all of our XSLT for the presentation, and I sort of wanted to be doing some of it myself. I'm glad that you started, and I'd understood you'd write one of the XSLT transformations, but are you okay with leaving some of this to write in my own way?

**Comment by ebeshero** [comment]
@HelenaSabel I don't mean for that to sound as if you've overstepped--it's just that there are things I'd like to be building on this project. I'm busy and and multi-tasking, as I am sure you are too, so I haven't had time to work on the XSLT in the past few days, but I'd like to try designing the project site and the facing views, and think about the web presentation and CSS. Some of this is because I am going to be presenting in Lyon, and because I need to be building the website for the project anyway. I suppose we should have been a little clearer about division of tasks and expectations regarding transformations and project development. If you'd like to continue concentrating attention on the tables, that would be really helpful, and give me a chance to work on the presentation of the texts a while.

**Comment by HelenaSabel** [comment]
You don't even have to ask, of course I am! I just thought that you would be very busy with the classes and the preparation of your presentations for the TEI Conference and just wanted to relieve you from some work.

**Comment by HelenaSabel** [comment]
Oops, we posted at the same time. 
It didn't sound as if you were telling me off at all: don't worry!

**Comment by ebeshero** [comment]
@HelenaSabel There is something to be said for preparing one's presentation from the code up. Part of how I'm "writing" my conference presentation involves thinking my way through a transformation of the project files. It probably makes the most sense for you to work on the tables because you and Stacey can map out the translation issues together--so I think I'd like you to keep working on that. I need to design facing views of texts on multiple projects right now, and I have some ideas I want to test here...so I guess I'd like to try this myself. You've probably saved me some time by working out a way to match from Montalvo to Southey, so thanks for that. I've got some other ideas, working from the Southey side back, for the side-by-side web view--and let's leave this issue open, because as I get to work on that, I'll post more here. Thanks for giving this a running start!
