### ISSUE TITLE
Unimportant minor characters

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#3]
How do we deal with those nameless characters (squires, passing observant, etc.) when they have a direct speech?
Do we give them a distinct ID to each one of them and then add them to the SI file, or do we create an ID that will identify _all_ of them? (something equal to "anonymous character")

**Comment by setriplette** [comment]
Hi Helena,

I think no ID at all for anonymous characters. I can’t imagine it being important to find them. Their dialogue is only important to me in comparison to Southey’s, so it’s quantity is more important than who said it.

When I know that the character gets a name later, I’ll ID them. With 300+ named characters, most of them not very important either, I’m not going to worry about the unnamed ones, with a couple of exceptions, like “el enano” and “la donzella de Denamarcha.” Those have some specificity.

I’m not sure what “anonymous” would get us above leaving resp untagged. Thoughts?

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Aug 25, 2015, at 10:13 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

How do we deal with those nameless characters (squires, passing observant, etc.) when they have a direct speech?
Do we give them a distinct ID to each one of them and then add them to the SI file, or do we create an ID that will identify all of them? (something equal to "anonymous character")

**Comment by HelenaSabel** [comment]
For counting purposes, it's the same to either count all the `<milestone/>` that have no `@resp` than counting those which have a particular one. I was more incline to create one anyway because that way we can be sure that all  `<milestone/>` have their ID. If we allow that some of them might not have it because they're not important, we might be missing an important one due to a human error.

**Comment by setriplette** [comment]
This makes sense. Then let’s create anon as an xml:id and let it stand for all those unnamed characters. I’ll add it to the SI right now and then into M21.

S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Aug 25, 2015, at 10:48 AM, Elisa Beshero-Bondar <notifications@github.com<mailto:notifications@github.com>> wrote:

For counting purposes, it's the same to either count all the <milestone/> that has no @resp than counting those which has a particular one. I was more incline to create one anyway because that way we can be sure that all <milestone/> have their ID. If we allow that some of them might not have it because they're not important, we might be missing an important one due to a human error.

**Comment by setriplette** [comment]
I made an entry for anon in the SI document. We'll leave Squire 1 as he is--I added that to `<persName>` for anon. Going forward, we'll assign all unnamed and patently unimportant character dialoge as `resp="#anon"`

**Comment by ebeshero** [comment]
I'll add a rule to our Schematron, then, to make sure that all `<milestone/>` elements with `@unit=said @ana='start'` must have an `@resp` attribute...will post in a few minutes!

**Comment by ebeshero** [comment]
Done! Schematron rule added.
