### ISSUE TITLE
Numbers on tables?

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#35]
Hi Helena,
We are having a question as to what the numbers in the column mean. They don't appear to be literally numbers of words. I know that larger red numbers mean more compression, but that's as far as I've understood.

**Comment by HelenaSabel** [comment]
I have calculated it by subtracting to Montavo's word number, Southey's word number and then dividing the result by Southey's word number. So if the result is 0, it means that they have used the same number of words; if it's negative, it means that Southey has actually "added" some words to his translation (that's why they are all greenish, because it's unusual). Then, as you said, the higher the number, the higher the compression is (1 would mean that Montalvo's text contained twice as many words as Southey). You can read them as percentages, and if the compression is higher that 70% then you'll see it red.
If you prefer to have the ratio or some other kind of comparison formula, it'd be easy to change.

**Comment by ebeshero** [comment]
Thanks, Helena. I posted a slide with the XSLT template rule to show how you calculated this. Maybe it would be easiest for others outside the project to read as a percentage, though it was easy to explain once I showed the template rule. Want to just convert those to percent values? @setriplette @HelenaSabel 

Our paper was very well-received, by the way! Syd Bauman says he's fascinated by our project, and he was cloning our GitHub after the panel yesterday! He says our use of feature-structures and @synch is kind of idiosyncratic and not quite what the TEI guidelines had in mind(!) but that's not really a big problem--just gave us some intense conversation over lunch. And I think we're just fine with the fs we developed. We might want to adjust our markup a little, but I'll open another issue about that.

**Comment by HelenaSabel** [comment]
I was confident the presentation would be a success, and I'm eager to see those issues ;-)

I'm going to read about ways to express relative change and difference to see if I find the best formula to express the compression/expansion issue. More soon.
