### ISSUE TITLE
Conference Prep!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Amadis-in-Translation#36]
@HelenaSabel Go have a look at our powerpoint slides--we're prepared now to speak tomorrow! You'll see yourself cited on the first slide and other places--wish you were here! 

In the morning before we present, I'll put all your pages up on the website and link out to them.

**Comment by HelenaSabel** [comment]
The presentation looks great and the contents are so neat! (And thank you for mentioning me). I wish I was there too, but I'm hoping for a full report with all the feedback you get ;-)

Since I didn't know your file name preferences, I didn't add the links of the alignment chapters to the toc2.html stylesheet, so I'm sorry for making you do that manually...

**Comment by HelenaSabel** [comment]
I reorganized the xslt and html folder so only the current and updated files are in the main folder and the old ones (which we might need for something) are in a subfolder named "log".

**Comment by ebeshero** [comment]
@HelenaSabel @setriplette The website with Helena's toc2 and alignment tables is up! Huzzah! I rearranged the menu just a little, for the moment. On the way to present!

**Comment by ebeshero** [comment]
I saw that! Many thanks, Helena! You really ARE here with us in spirit!
Hugs,
Elisa and Stacey of Helistacea
