### ISSUE TITLE
Montalvo 21 is ready for proofreading by Helena.

### ISSUE THREAD

**Issue by setriplette** [ebeshero/Amadis-in-Translation#4]

**Comment by HelenaSabel** [comment]
I think this is a very efficient system. If I don't have any doubts, I'll close the issue after finishing with it.

**Comment by ebeshero** [comment]
:-)

**Comment by ebeshero** [comment]
I just added the "help wanted" label and a GitHub Milestone named "Proofreading" to this: We may want to use these to systematically to label Proofreading tasks.

**Comment by HelenaSabel** [comment]
Chapter 21 is finished. 
@setriplette, if you open the file and press "History" and then click over the commits with "proofread" in the name, you can keep track of the changes (although in the first one, I indented the file and Github considers that's a code replacement, so you'll see some color-coded changes that don't contain any modifications).
There were two or so punctuation signs missing which meant some extra clauses. After running the ID clause transformation, Github thinks I've completely changed the file: that's why I don't recommend going through that last commit.
