### ISSUE TITLE
chapter IDs

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#41]
Dear @ebeshero and @setriplette  The Schematron rule to check the chapter ID doesn't work on Montalvo's first chapters (M0 and M1) because there is no Roman number in the `<head>`.
I am inclined to do a regularization of the chapter heads using `<choice>` so we can have both the original head and a more consistent one. The first one is "Comiença la obra" which I don't think will need any regularization (do you agree, Stacey?), but for the next two I would replace:
`<head>Capítulo primero <locus from="iiii-r" to="v-v"/></head>`
`<head><choice><orig>Capítulo primero</orig><reg>Capítulo I</reg></choice> <locus from="iiii-r" to="v-v"/></head>`
and
`<head>Capítu. II <locus from="v-v" to="vii-v"/></head>`
with
`<head><choice><orig>Capítu. II</orig><reg>Capítulo II</reg></choice> <locus from="v-v" to="vii-v"/></head>`
That way we could use the regularized forms for the table of contents, for example, and keep the original ones in the reading views.
What do you think?

**Comment by setriplette** [comment]
This works for me, Helena!

I’m following all of this week's discussions as best I can and admiring your work from afar, but I admit I’ve taken a break from transcription this week to get back to my book. What I have to report is that the Herberay French translation of Amadis has some very interesting additions (and some that are in extremely poor taste), if we ever want to take that on.

Hugs,
S

—
Stacey Triplette
Assistant Professor of Spanish and French
Humanities Division
University of Pittsburgh at Greensburg
Faculty Office Building 200
150 Finoli Drive
Greensburg, PA 15601

On Nov 6, 2015, at 10:13 AM, Helena <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear @ebesherohttps://github.com/ebeshero and @setriplettehttps://github.com/setriplette The Schematron rule to check the chapter ID doesn't work on Montalvo's first chapters (M0 and M1) because there is no Roman number in the <head>.
I am inclined to do a regularization of the chapter heads using <choice> so we can have both the original head and a more consistent one. The first one is "Comiença la obra" which I don't think will need any regularization (do you agree, Stacey?), but for the next two I would replace:
<head>Capítulo primero <locus from="iiii-r" to="v-v"/></head>
<head><choice><orig>Capítulo primero</orig><reg>Capítulo I</reg></choice> <locus from="iiii-r" to="v-v"/></head>
and
Capítu. II
with
Capítu. IICapítulo II `
That way we could use the regularized forms for the table of contents, for example, and keep the original ones in the reading views.
What do you think?

**Comment by HelenaSabel** [comment]
I'm not working on transcribing either, but I hope I'll get to it soon.
I made the changes I proposed, so I'm keeping the issue open until @ebeshero reviews them

**Comment by ebeshero** [comment]
I'm taking a look very soon! Sorry for the delay: I'm facing an onslaught of student questions on Schematron (ironically enough) today!

**Comment by ebeshero** [comment]
That use of orig and reg makes sense to me, too, @HelenaSabel. I bet I can modify my Schematron rule so it doesn't apply to the first one or two chapters that don't have Roman numerals. I only set it as we were working on later chapters and I noticed we could easily forget to update the chapter number when starting a new chapter file from an earlier file.

**Comment by ebeshero** [comment]
Okay! I see you've already modified the schematron file so it misses M0. Looks good to me! Thanks, @HelenaSabel.
