### ISSUE TITLE
coding folia numbers

### ISSUE THREAD

**Issue by HelenaSabel** [ebeshero/Amadis-in-Translation#42]
I've noticed that in one of the chapters we had coded the page number differently (with a dot before the recto/verso specification instead of a hyphen) so I fixed that one and added a Schematron rule so as to be consistent with those.

**Comment by ebeshero** [comment]
@HelenaSabel I noticed two small problems with the new schematron rule for recto / verso specification: The `|` was part of a character set (inside square brackets with r and v), so you could actually type a `|` instead of r or v in the @from and @to attribute on `<locus>`. Also, you could continue on to add characters, like rqqqqq. So I just added a little tweak and changed the Schematron test thus:

`<pattern>
    <rule context="tei:div[@type eq 'chapter'][@xml:id[contains(., 'M')]]/tei:head/tei:locus">
      <assert test="matches(@from, '[ivxlcdm]+\-(r|v)$') and matches(@to, '[ivxlcdm]+\-(r|v)$')">The number of folia must be coded as a Roman numeral (lower case), followed by a hyphen and either the letter 'r' or 'v'</assert>
    </rule>
  </pattern>`

The change is just from this: `[r|v]` to this: `(r|v)$` I discover that you can use the end-of-line `$` to indicate where you want an attribute value to end, to prevent additional characters from being added.
