### ISSUE TITLE
Becca's Git Shell Tutorial: Test Run?

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/Amadis-in-Translation#51]
@setriplette @HelenaSabel @sydb @rjp43  My student, Becca Parker, has been working hard on a Git Shell tutorial for use with our digital humanities students, to teach them how to use GitHub entirely from command line clients. (To this point our students have been Mac and PC users and tend to start with a graphical user interface or "GUI" client, which has now and again caused us some problems.) Becca herself works in a Windows environment and would appreciate some cross-platform information from Mac and Linux users, and really any suggestions wherever her tutorial gets bumpy and rough! 

Here's a link to the tutorial: http://newtfire.org/dh/explainGitShell.html

We've been test-running it on some Pitt students this week, and a couple of my students (totally new to command line) report they're more comfortable with it now! 

Stacey, you're my next faculty colleague "guinea pig," so I'll really appreciate your advice as you work through this and try to familiarize yourself with forking and branching! Here's where we're collecting feedback: https://github.com/ebeshero/newtFire-webDev/issues/27

**Comment by andrewntz23** [comment]
Hi all,

Just finished reading through this, it's a really good tutorial! There are a few typos, which is the only thing I would change:
1. Under the "Why use the Git Shell (command line)" heading, it says "reposiotories" instead of "repositories"
2. "Functionability " is used once; it may be a technical term that I haven't heard of, but I'm not sure that its a real word
3. Point 3 under "Basic Git workflow:" "driectory " needs changed

Besides that it is a really impressive tutorial! Great work!
